plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
    id "me.modmuss50.mod-publish-plugin"
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    implementation include("com.electronwill.night-config:core:3.8.1")
    implementation include("com.electronwill.night-config:toml:3.8.1")

    compileOnly "mezz.jei:jei-${dependencies_mc_version}-fabric-api:${jei_version}"
//    runtimeOnly "mezz.jei:jei-${dependencies_mc_version}-fabric:${jei_version}"

    compileOnly "dev.ftb.mods:ftb-library-fabric:26.1.2.6"
    compileOnly "dev.ftb.mods:ftb-teams-fabric:26.1.2.4"
    compileOnly "dev.ftb.mods:ftb-quests-fabric:26.1.2.1-SNAPSHOT"

    implementation include("com.coolerpromc.coolerconfig:coolerconfig-fabric-${minecraft_version}:${cooler_config_version}")

    compileOnly "curse.maven:travelers-backpack-fabric-541171:8071343"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.classtweaker")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}

sourceSets.main.resources{ srcDir rootProject.project(':common').file('src/generated/resources/').getAbsolutePath() }

publishMods {
    file.set(jar.archiveFile)
    type = STABLE
    modLoaders.add("fabric")
    changelog = rootProject.file("changelog.md").text
    displayName = mod_id + "-" + project.version + "+" + minecraft_version + "-fabric"

    curseforge {
        projectId = "1244428"
        accessToken = findProperty("CF_TOKEN")
        minecraftVersions.add(minecraft_version)

        client = true
        server = true
    }

    modrinth {
        projectId = '9cz66Qto'
        accessToken = findProperty("MODRINTH_TOKEN")
        minecraftVersions.add(minecraft_version)
    }
}