plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.173'
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    maven { url = 'https://maven.minecraftforge.net/' }
    maven { // TOP
        url "https://maven.k-4u.nl"
    }
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven { url 'https://modmaven.dev/' }
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    maven { url "https://maven.architectury.dev/" }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        arguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

accessTransformers {
    file('src/main/resources/META-INF/accesstransformer.cfg')
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    implementation "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    implementation "dev.architectury:architectury-neoforge:${architectury_version}"
    implementation "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"
    compileOnly "me.shedaniel:RoughlyEnoughItems-api-neoforge:${rei_version}"
//    runtimeOnly  "me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}"

    implementation "curse.maven:chipped-456956:5813117"
    implementation "curse.maven:productivetrees-867074:6263281"
    implementation "curse.maven:resourceful-lib-570073:5973188"
    implementation "curse.maven:athena-841890:6669522"

    implementation "curse.maven:ftb-quests-forge-289412:6874989"
    implementation "curse.maven:ftb-library-forge-404465:6874538"
    implementation "curse.maven:ftb-teams-forge-404468:6930910"

    implementation "curse.maven:travelers-backpack-321117:7240666"

    implementation "curse.maven:owo-lib-532610:6785734"
    implementation "curse.maven:defaulted-1177694:7216366"
    implementation "curse.maven:atlas-core-1073789:7455630"
    implementation "curse.maven:forgified-fabric-api-889079:7377533"
    implementation "curse.maven:combatify-658569:7169149"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId = mod_id
            from components.java
        }
    }
    repositories {
        mavenLocal()
        maven {
            url = findProperty("repsy_url")
            credentials {
                username = findProperty("repsy_username")
                password = findProperty("repsy_password")
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

publishMods {
    file.set(jar.archiveFile)
    type = STABLE
    modLoaders.add("neoforge")
    changelog = file("changelog.md").text
    displayName = mod_id + "-" + mod_version

    curseforge {
        projectId = "1244428"
        accessToken = findProperty("CF_TOKEN")
        minecraftVersions.add(minecraft_version)
    }

    modrinth {
        projectId = '9cz66Qto'
        accessToken = findProperty("MODRINTH_TOKEN")
        minecraftVersions.add(minecraft_version)
    }
}