# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=25w42a
yarn_mappings=25w42a+build.9
loader_version=0.17.3

rei_version=19.0.805

# Mod Properties
mod_version=1.9.0+25w42a-fabric
maven_group=com.coolerpromc.uncrafteverything
archives_base_name=uncrafteverything

# Dependencies
fabric_version=0.136.0+1.21.11
