# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1-snapshot-10
loader_version=0.18.4

rei_version=19.0.805
jei_version=28.3.0.11

# Mod Properties
mod_version=2.1.2+26.1-snapshot-19-fabric
maven_group=com.coolerpromc
archives_base_name=uncrafteverything

# Dependencies
fabric_version=0.143.6+26.1
