name: 🐞 Bug Report
description: Report a bug to help us improve.
title: "[Bug]: "
labels: [bug]
body:
  - type: input
    id: bug_description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "The game crashes when I open the inventory..."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: input
    id: expected_behavior
    attributes:
      label: Expected behavior
      placeholder: "The inventory should open without crashing."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: "Drag and drop or paste images here."

  - type: input
    id: mod_version
    attributes:
      label: Mod Version
      placeholder: "e.g. v1.3.0"
    validations:
      required: true

  - type: input
    id: minecraft_version
    attributes:
      label: Minecraft Version
      placeholder: "e.g. 1.21.5"
    validations:
      required: true

  - type: input
    id: mod_loader
    attributes:
      label: Mod Loader
      placeholder: "e.g. NeoForge, Forge, Fabric, Quilt"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
